######################################
#
# KLEARNOW CONFIDENTIAL
# __________________
#
#  Copyright (c) 2018 - 2020 KLEARNOW Corporation.
#  All Rights Reserved.
#
# NOTICE:  All information contained herein is, and remains
# the property of KLEARNOW Corporation and its suppliers,
# if any.  The intellectual and technical concepts contained
# herein are proprietary to KLEARNOW Corporation
# and its suppliers and may be covered by U.S. and Foreign Patents,
# patents in process, and are protected by trade secret or copyright law.
# Dissemination of this information or reproduction of this material
# is strictly forbidden unless prior written permission is obtained
# from KLEARNOW Corporation.
# apiVersion: v1
# kind: Service
# metadata:
#  name: tg-kdesigns
#  namespace: ${cluster_namespace}
#  annotations:
#    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: ${ssl_cert_arn}
# spec:
#  type: LoadBalancer
#  selector:
#   app: tg-kdesigns
#  ports:
#    - port: 443
#      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: tg-kdesigns
 namespace: ${cluster_namespace}
spec:
 replicas: ${pod_replicas}
 selector:
    matchLabels:
      app: tg-kdesigns
 template:
   metadata:
     labels:
      app: tg-kdesigns
   spec:
     tolerations:
     - key: dedicated
       operator: Equal
       value: tg-cluster
       effect: NoSchedule

     nodeSelector:
       nodegroup: tg-cluster

     securityContext:
        seccompProfile:
          type: RuntimeDefault  # Set seccompProfile at the pod level
        runAsUser: 101         # Run as user with UID 101
        runAsGroup: 101        # Run as group with GID 101
        fsGroup: 101           # Set fsGroup to 101
        runAsNonRoot: true      # Ensure the container doesn't run as root
     containers:
       - name: tg-kdesigns
         image: ${docker_image}
         imagePullPolicy: Always
         resources:
           requests:
             memory: "64Mi"
             cpu: "250m"
           limits:
             memory: "128Mi"
             cpu: "500m"
         env:
           - name: NODE_ENV
             value: ${cluster_namespace}
           - name: REACT_APP_BASE_API_URL
             valueFrom:
               configMapKeyRef:
                 name: microservices-vault
                 key: REACT_APP_BASE_API_URL
           - name: REACT_APP_ENVIRONMENT
             valueFrom:
               configMapKeyRef:
                 name: microservices-vault
                 key: KX_ENVIRONMENT               
         ports:
           - containerPort: 8080
         securityContext:
          allowPrivilegeEscalation: false  # Prevent privilege escalation for the container
         resources: {}
     restartPolicy: Always
